CREATE TABLE IF NOT EXISTS presentation.presentations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS presentation.slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_bytes BYTEA,
    text VARCHAR(255),
    text_color VARCHAR(255),
    presentation_id BIGINT,
    slide_order INTEGER,
    CONSTRAINT fk_slides_presentation
        FOREIGN KEY (presentation_id)
        REFERENCES presentation.presentations (id)
        ON DELETE CASCADE
);
