CREATE TABLE IF NOT EXISTS presentation.templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    file_name VARCHAR(255),
    file_bytes BYTEA,
    slide_count INTEGER
);
